//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Features { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
